db-uri = "postgres://authenticator:${AUTHENTICATOR_PASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}"
db-schemas = "api"
db-anon-role = "web_anon"
jwt-secret = "${JWT_SECRET}"
server-host = "0.0.0.0"
server-port = 3000
