replicaCount: 1

image:
  repository: python
  pullPolicy: IfNotPresent
  tag: "3.11-slim"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  hosts:
    - host: retail-frontend.local
      paths:
        - path: /

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 10s
