slug: end-to-end-cicd-microservice-pipeline
title: End-to-End CICD Microservice Pipeline
playground: Full CI/CD Playground
group: 
status: active
difficulty: advanced
playground_link: https://kodekloud.com/playgrounds/playground-ci-cd
mapped_lab_env: TBD
clickup_page: 13h9cc-138476
