pipeline {
    agent {
        label "docker"
    }
    stages {
        stage('Checkout code') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'http://git-server:3000/max/weather-advisory.git']]])
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker build -t docker-host:5000/weather-api:latest .'
            }
        }
        stage('Publish to Registry') {
            steps {
                sh 'docker login -u dock_user -p dock_password docker-host:5000'
                sh 'docker push docker-host:5000/weather-api:latest'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                withKubeConfig(caCertificate: "${KUBE_CERT}", clusterName: 'kubernetes', contextName: 'kubernetes-admin@kubernetes', credentialsId: 'my-kube-config-credentials', namespace: 'default', restrictKubeConfigAccess: false, serverUrl: 'https://jump-host:6443') 
                {
                    sh 'kubectl apply -f manifests.yaml'
                    sh 'kubectl rollout restart deployment/weather-advisory'
                    sh 'kubectl rollout status deployment/weather-advisory'
                }
            }
        }  
    }
}
