slug: automated-cloud-foundation
title: Automated Cloud Foundation
playground: AWS Terraform Playground
group: 
status: active
difficulty: intermediate
playground_link: https://kodekloud.com/playgrounds/playground-terraform-aws
mapped_lab_env: TBD
clickup_page: 13h9cc-136116
