slug: config-based-arch-workspace
title: Config-Based Arch Workspace
playground: Arch Linux Playground
group: 
status: active
difficulty: intermediate
playground_link: https://kodekloud.com/playgrounds/playground-arch-linux
mapped_lab_env: TBD
clickup_page: 13h9cc-137996
