slug: relational-database-initialization-and-schema-design
title: Relational Database Initialization and Schema Design
playground: MariaDB Playground
group: Database
status: active
difficulty: beginner
playground_link: TBD
mapped_lab_env: TBD
clickup_page: 13h9cc-144736
