slug: multi-node-high-availability
title: Multi-Node High Availability
playground: Ubuntu Playground
group: 
status: active
difficulty: intermediate
playground_link: https://kodekloud.com/playgrounds/playground-ubuntu-20-04-multi-node
mapped_lab_env: TBD
clickup_page: 13h9cc-136076
