slug: decoupled-gitops-inventory-pipeline
title: Decoupled GitOps Inventory Pipeline
playground: GitLab | AWS Playground
group: 
status: active
difficulty: advanced
playground_link: https://kodekloud.com/playgrounds
mapped_lab_env: TBD
clickup_page: 13h9cc-144416
