slug: enterprise-hr-database-audit
title: Enterprise HR Database Audit
playground: MySQL Playground
group: Database
status: active
difficulty: intermediate
playground_link: https://kodekloud.com/playgrounds/playground-mysql
mapped_lab_env: TBD
clickup_page: 13h9cc-143096
