slug: monolith-to-microservices
title: Monolith to Microservices
playground: Kubernetes Playground
group: 
status: active
difficulty: intermediate
playground_link: https://kodekloud.com/playgrounds/playground-kubernetes-single-node-latest
mapped_lab_env: TBD
clickup_page: 13h9cc-136016
