slug: database-sharding-and-data-migration
title: Database Sharding and Data Migration
playground: Docker Playground
group: 
status: active
difficulty: advanced
playground_link: https://kodekloud.com/playgrounds/playground-docker
mapped_lab_env: TBD
clickup_page: 13h9cc-135916
